-- Database initialization script for trpc-agent-service.
--
-- Role boundary: this is a genesis script, executed once by the postgres
-- container on first startup of an empty data volume (the
-- /docker-entrypoint-initdb.d/ mechanism). All later schema changes go
-- through an incremental migration tool (golang-migrate / goose); this file
-- is the 000001 baseline and must only change incrementally, never
-- destructively.

-- pgvector: vector search for Knowledge.
CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- Tenant: base info and tenant-level policy config (JSONB carries dynamic
-- config, avoiding frequent DDL)
-- ---------------------------------------------------------------------------
CREATE TABLE tenant (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name           varchar(128) NOT NULL,
    model_config   jsonb,
    tool_policy    jsonb,
    audit_policy   jsonb,
    -- Data-backend overrides (a controlled menu), e.g.
    -- {"session":{"type":"redis","dsn_ref":"t42-redis"}}. Empty means the
    -- platform-recommended stack. Changes must go through the migration
    -- procedure; live switching is forbidden.
    storage_config jsonb,
    status         varchar(32) NOT NULL DEFAULT 'active',
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_tenant_status ON tenant (status);

-- ---------------------------------------------------------------------------
-- Agent app: per-tenant agent configuration, with versioning and gray release
-- ---------------------------------------------------------------------------
CREATE TABLE agent_app (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  uuid         NOT NULL REFERENCES tenant (id),
    name       varchar(128) NOT NULL,
    agent_type varchar(64)  NOT NULL,
    config     jsonb        NOT NULL, -- prompt, model and tool config
    version    int          NOT NULL,
    status     varchar(32)  NOT NULL DEFAULT 'draft', -- draft / published / disabled
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_agent_app_version UNIQUE (tenant_id, name, version)
);
-- At most one published version per (tenant, app name); publish/rollback is atomic.
CREATE UNIQUE INDEX uk_agent_app_published
    ON agent_app (tenant_id, name) WHERE status = 'published';
CREATE INDEX idx_agent_app_tenant ON agent_app (tenant_id);

-- ---------------------------------------------------------------------------
-- Channel binding: binds external channels to agent apps. Secrets are stored
-- as references only, never in plaintext.
-- ---------------------------------------------------------------------------
CREATE TABLE channel_binding (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid         NOT NULL REFERENCES tenant (id),
    channel      varchar(64)  NOT NULL, -- wecom / wechat_kf / mock ...
    app_id       uuid         NOT NULL REFERENCES agent_app (id),
    webhook_path varchar(256) NOT NULL,
    token_ref    varchar(256),          -- token secret reference; no plaintext
    aeskey_ref   varchar(256),          -- AES key secret reference; no plaintext
    -- Channel-specific config, e.g. wecom corp_id/agent_id; sensitive fields
    -- are still stored as references only.
    config       jsonb,
    status       varchar(32)  NOT NULL DEFAULT 'active',
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_channel_webhook UNIQUE (webhook_path) -- callback path is globally unique
);
CREATE INDEX idx_channel_binding_app ON channel_binding (app_id);
CREATE INDEX idx_channel_binding_tenant ON channel_binding (tenant_id, channel);

-- ---------------------------------------------------------------------------
-- Session: current state snapshot; full history lives in session_event.
-- session_key is generated by the Channel Adapter:
-- dm:{channel}:{user} / group:{channel}:{chat}
-- ---------------------------------------------------------------------------
CREATE TABLE session (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   uuid         NOT NULL,
    app_id      uuid         NOT NULL REFERENCES agent_app (id),
    session_key varchar(256) NOT NULL,
    user_id     varchar(128) NOT NULL,
    channel     varchar(64)  NOT NULL,
    state       jsonb        NOT NULL DEFAULT '{}', -- materialized snapshot; the event stream is the source of truth
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_session_app_key UNIQUE (app_id, session_key)
);
CREATE INDEX idx_session_user ON session (tenant_id, user_id);
CREATE INDEX idx_session_updated_at ON session (updated_at);

-- ---------------------------------------------------------------------------
-- Session event: append-only. UNIQUE (session_id, event_seq) guarantees
-- ordering without duplicates and doubles as the execution-layer idempotency
-- backstop for Stream redeliveries. Old rows are archived monthly; no
-- declarative partitioning.
-- ---------------------------------------------------------------------------
CREATE TABLE session_event (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id uuid        NOT NULL REFERENCES session (id),
    event_seq  bigint      NOT NULL,
    event      jsonb       NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_session_event_seq UNIQUE (session_id, event_seq)
);

-- ---------------------------------------------------------------------------
-- Memory item: app_id non-null = app-private, NULL = tenant-shared;
-- soft delete backs the "user asks to be forgotten" requirement.
-- ---------------------------------------------------------------------------
CREATE TABLE memory_item (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    uuid         NOT NULL,
    app_id       uuid,                  -- NULL means tenant-shared memory
    user_id      varchar(128) NOT NULL,
    content      text         NOT NULL,
    embedding_id varchar(256),          -- vector ID in the vector store (externalized for easier migration)
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    deleted_at   timestamptz            -- NULL means active
);
CREATE INDEX idx_memory_item_user ON memory_item (tenant_id, user_id, app_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- Summary: summary text + coverage cursor; crash recovery replays
-- incrementally from covered_event_id onward.
-- ---------------------------------------------------------------------------
CREATE TABLE summary (
    session_id       uuid PRIMARY KEY REFERENCES session (id),
    summary_text     text        NOT NULL,
    -- Logical reference without a foreign key: session_event rows get
    -- archived away, and a hard FK would block archival.
    covered_event_id uuid        NOT NULL,
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Audit log: routine events are written asynchronously in batches; critical
-- decisions (deny/review) are written synchronously (compliance red line).
-- Old rows are archived monthly into the same-shaped audit_log_archive.
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id         uuid         NOT NULL,
    channel           varchar(64),
    user_id           varchar(128),
    session_id        uuid,
    agent_name        varchar(128),
    tool_name         varchar(128),
    decision          varchar(32)  NOT NULL, -- allow / deny / review / review_timeout
    latency_ms        int,
    error_type        varchar(64),
    cost              numeric(12, 6),
    prompt_tokens     int,
    completion_tokens int,
    trace_id          varchar(128),
    created_at        timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_tenant_time ON audit_log (tenant_id, created_at);
CREATE INDEX idx_audit_session ON audit_log (session_id);
CREATE INDEX idx_audit_trace ON audit_log (trace_id);
